name: Update Events

on:
  schedule:
    - cron: "0 8 * * *"   # Ogni giorno alle 9:00 italiane (8:00 UTC)
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add events.json
          git commit -m "Aggiornamento automatico eventi [skip ci]" || echo "Nessun cambiamento"
          git push
